name: BC Check
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  bc_check:
    name: Backwards Compatibility Check
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: composer install
      - name: Transpile to 7.4
        run: php vendor/bin/rector process --no-diffs --no-progress-bar --config rector.74.php src
      - name: Update composer.json version
        run: 'sed -i -e ''s/"php": "\^8.0"/"php": "\^7.4"/'' composer.json'
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Install BC checker
        run: composer require --dev roave/backward-compatibility-check
      - name: Check for BC breaks
        run: vendor/bin/roave-backward-compatibility-check
